name: Python Security

on:
  workflow_call:
    inputs:
      working-directory:
        description: Relative path under $GITHUB_WORKSPACE where the project is located.
        default: .
        required: false
        type: string

jobs:
  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checks
        uses: equisoft-actions/codeql@v1
        with:
          languages: python
          working-directory: ${{ inputs.working-directory }}
