name: Python Security

on:
  workflow_call:
    inputs:
      defectdojo-engagement:
        description: "DefectDojo Engagement name or id"
        default: ""
        required: false
        type: string
      dependency-track-project-name:
        description: Project name for Dependency Track.
        required: false
        type: string
      dependency-track-project-version:
        description: Project name for Dependency Track. Typically the default branch unless multiple forks are maintained.
        default: main
        required: false
        type: string
      publish-reports:
        description: Publish the generated reports to the Security Operation Center. Defaults to false.
        default: false
        required: false
        type: boolean
      report-retention-days:
        description: "Duration in days to preserve reports."
        required: false
        default: "5"
        type: string
      working-directory:
        description: Relative path under $GITHUB_WORKSPACE where the project is located.
        default: .
        required: false
        type: string
    secrets:
      defectdojo-url:
        description: DefectDojo URL
        required: false
      defectdojo-token:
        description: DefectDojo API Token
        required: false
      dependency-track-url:
        description: URL to the Dependency Track instance to publish the SBOM to.
        required: false
      dependency-track-api-key:
        description: API key of the Dependency Track instance.
        required: false

jobs:
  secrets:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run secret scanner
        uses: kronostechnologies/actions/scan-secrets@v0.0.22

  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checks
        uses: equisoft-actions/semgrep@v1.0.0
        with:
          defectdojo-engagement: ${{ inputs.defectdojo-engagement }}
          defectdojo-publish: ${{ inputs.publish-reports }}
          defectdojo-token: ${{ secrets.defectdojo-token }}
          defectdojo-url: ${{ secrets.defectdojo-url }}
          language: py
          report-retention-days: ${{ inputs.report-retention-days }}
          working-directory: ${{ inputs.working-directory }}

  sbom:
    name: SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: equisoft-actions/setup-python@v1.1.0

      - name: Generate SBOM
        uses: equisoft-actions/pipenv-sbom@v1.0.0
        with:
          dependency-track-api-key: ${{ secrets.dependency-track-api-key }}
          dependency-track-url: ${{ secrets.dependency-track-url }}
          dependency-track-project-name: ${{ inputs.dependency-track-project-name }}
          dependency-track-project-version: ${{ inputs.dependency-track-project-version }}
          publish: ${{ inputs.publish-reports }}
          report-retention-days: ${{ inputs.report-retention-days }}
          working-directory: ${{ inputs.working-directory }}
