name: Python Quality Checks

on:
  workflow_call:
    inputs:
      workflow-path:
        description: Workflow file used for change detection.
        required: false
        type: string
      working-directory:
        description: Relative path under $GITHUB_WORKSPACE where the project is located.
        required: false
        type: string

jobs:
  pre-checks:
    name: Pre-checks
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}

    steps:
      - name: Skip Check
        id: skip-check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content
          do_not_skip: >-
            [
              "push",
              "schedule",
              "workflow_dispatch"
            ]
          paths: >-
            [
              ".tool-versions",
              "${{ inputs.workflow-path }}",
              "${{ inputs.working-directory }}/**"
            ]
          skip_after_successful_duplicate: true

  setup:
    name: Setup
    needs: [ pre-checks ]
    if: ${{ needs.pre_checks.outputs.should-skip != 'true' }}
    runs-on: ubuntu-latest
    outputs:
      dependencies-manager: ${{ steps.setup-python.outputs.dependencies-manager }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        id: setup-python
        uses: equisoft-actions/setup-python@v1

  unit-tests:
    name: Unit tests
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: equisoft-actions/setup-python@v1

      - name: Run pytest
        working-directory: ${{ inputs.working-directory }}
        run: ${{ needs.setup.outputs.dependencies-manager }} run pytest -v

  type-check:
    name: Type check
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: equisoft-actions/setup-python@v1

      - name: Run pytype
        working-directory: ${{ inputs.working-directory }}
        run: ${{ needs.setup.outputs.dependencies-manager }} run pytype

  code-style:
    name: Code style
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: equisoft-actions/setup-python@v1

      - name: Run codestyle
        working-directory: ${{ inputs.working-directory }}
        run: ${{ needs.setup.outputs.dependencies-manager }} run ruff check --select ANN --select E --select F --select I --select N --select PD --select W --ignore ANN101 --ignore ANN102 --ignore ANN401 --ignore PD015 --ignore PD901 --statistics ./
